### ISSUE TITLE
Question: DNS not working as expected

### ISSUE THREAD

**Issue by daniel-wtd** [containers/dnsname#17]
Hi all,

I am on Fedora 31 with podman 1.8.1, podman-plugins is installed.

I have done the following:

1. Create a new network
```
podman network create test1
podman network inspect test1

[
	{
		"cniVersion": "0.4.0",
		"name": "test1",
		"plugins": [
			{
				"bridge": "cni-podman1",
				"ipMasq": true,
				"ipam": {
					"ranges": [
						[
							{
								"gateway": "10.89.0.1",
								"subnet": "10.89.0.0/24"
							}
						]
					],
					"routes": [
						{
							"dst": "0.0.0.0/0"
						}
					],
					"type": "host-local"
				},
				"isGateway": true,
				"type": "bridge"
			},
			{
				"capabilities": {
					"portMappings": true
				},
				"type": "portmap"
			},
			{
				"backend": "",
				"type": "firewall"
			},
			{
				"domainName": "dns.podman",
				"type": "dnsname"
			}
		]
	}
]
```

Afterwards I created two containers

```
podman run -it --rm --name foo --hostname foo --network test1 alpine sh
podman run -it --rm --name bar --hostname bar --network test1 alpine sh
```

I wanted to test the dns / ping from container foo

```
/ # ping foo
ping: bad address 'foo'
/ # nslookup foo
Server:		10.89.0.1
Address:	10.89.0.1:53

** server can't find foo.home: NXDOMAIN

** server can't find foo.home: NXDOMAIN
```

**Comment by daniel-wtd** [comment]
minor addition: in the alpine container a search domain is set. after unsetting it, the result is similar.

**Comment by daniel-wtd** [comment]
the hostnames are also not resolvable from the host underneath the containers, when using the proper interface.

**Comment by daniel-wtd** [comment]
I had a deeper look at the dnsmasq.conf provided by the plugin.

I have added the following:
```
address=/foo/10.88.0.71
log-queries
log-dhcp
```
And it was working after restarting all containers

Before I was seeing some "NODATA-IPv4" logs, when trying too lookup records.

**Comment by rhatdan** [comment]
Does this mean this is not an issue then?

**Comment by daniel-wtd** [comment]
it is an issue, but seems not to be directly related to dnsname plugin itself, but the way dnsmasq is handled/configured/used.

in IRC, @baude and I also discussed, that the "hup" is working seemingly well. Nevertheless, we it is not working as expect, since DNS is not working without overwriting automatically generated files.

**Comment by daniel-wtd** [comment]
Just a minute ago, there was an update for dnsmasq available. After applying and rebooting, the thing is working oO

I will validate this today on the other machine and come back asap.

**Comment by daniel-wtd** [comment]
Hi all,

I can confirm, that with the last update from dnsmasq, eversything is working fine in f31, silverblue and iot :)
