### ISSUE TITLE
Please, correct README_PODMAN.md

### ISSUE THREAD

**Issue by mkwapisz** [containers/dnsname#37]
Example: container name resolution
sudo podman run -dt --name web --network **foobar** quay.io/libpod/alpine_nginx:latest 5139d65d22135e9ecab511559d863754550894a32285befd94dab231017048c2
Note: we use the --network foobar here. Also, in this test image, the nginx server will respond with podman rulez on an http request.
sudo podman run -it --name client --network **cni-podman1** quay.io/libpod/alpine_nginx:latest curl http://web/ podman rulez

This example suggests that it is possible to enable name resolution between containers in different networks. It is against a statement at the beginning of the document: The containers will only be able to resolve each other if they are on the same CNI network.

**Comment by rhatdan** [comment]
Could you open a PR to make these changes?

**Comment by xordspar0** [comment]
This is fixed in #48.
