### ISSUE TITLE
dnsname - plugin should be in /usr/libexec/cni 

### ISSUE THREAD

**Issue by atarlov** [containers/dnsname#38]
I played a bit with the dns plugin. 

- dnsmasq should be installed (via yum install dnsmasq) 
- the plugin should be available in the cni 

/usr/libexec/cni
.
├── bandwidth
├── bridge
├── dhcp
**├── dnsname**
├── firewall

However i installed it via **podman-plugins**  from the @devel_kubic_libcontainers_testing . would be it be included in  containernetworking-plugins or will be a separate rpm from version v2 of podman ?

**Comment by baude** [comment]
you dont mention the distribution you are playing with.  but for fedora proper, it is correct.  upstream rejected the plugin which is why it is not shipped with it.  not much we can do there.

**Comment by atarlov** [comment]
[atarlov@localhost ~]$ cat /etc/*release
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"


@baude  is it going to be shipped in Podman V2.0 with RHEL 8.3 ? We are in a phase to migrate from docker to podman and need this plugin for dns resolution

**Comment by baude** [comment]
8.3.1

**Comment by domq** [comment]
[Unfortunately this is still not working for RHEL 8.3](https://github.com/containers/podman/issues/8365)

**Comment by rhatdan** [comment]
RHEL 8.3.1 is supposed to ship in February.  But this is not an upstream issue, so closing.
