### ISSUE TITLE
Option --network-alias still not working

### ISSUE THREAD

**Issue by dashohoxha** [containers/dnsname#46]
Something seems to be wrong with `netConf`, because `aliases` on this line is always empty: https://github.com/containers/dnsname/blob/master/plugins/meta/dnsname/main.go#L87
However I am not able to debug it further or to fix it.

**Comment by baude** [comment]
context? reproducer? versions?

**Comment by dashohoxha** [comment]
Latest packages on ubuntu:
```
# apt list podman
podman/unknown,now 2.2.0~2 amd64 [installed]

# apt list podman-plugins
podman-plugins/unknown,now 1.1.1~1 amd64 [installed,automatic]

# podman --version
podman version 2.2.0
```

Create a new network:
```
# podman network create testnet
/etc/cni/net.d/testnet.conflist
```

This is supposed to enable dns plugin by default, since `podman network create --help` shows also an option `--disable-dns`.
Indead `/etc/cni/net.d/testnet.conflist` contains also this sippet:

```
      {
         "type": "dnsname",
         "domainName": "dns.podman",
         "capabilities": {
            "aliases": true
         }
      }
```

For testing:

```
# podman run -dt --name test \
      --network testnet \
      --network-alias example.org \
      quay.io/libpod/alpine_nginx:latest

# cat /run/user/0/containers/cni/dnsname/testnet/addnhosts
10.89.2.2       test    example.org

# podman run -it --rm \
      --network testnet \
      quay.io/libpod/alpine_nginx:latest \
      curl http://example.org/
podman rulez
```

And... it works!!!

Turns out that I was using an old network, that was created before updating to the latest version of podman, and the capability of aliases was not enabled (as you said).

So, it is actually working as expected.
Thanks.

**Comment by baude** [comment]
ty! and happy it does!
