### ISSUE TITLE
README_PODMAN.md: "http://web" is a typo of "http://web.dns.podman" ?

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/dnsname#52]
https://github.com/containers/dnsname/blob/966301eef1b1ec5cb9f3d3bc1deb79fa4136abce/README_PODMAN.md#example-container-name-resolution

> sudo podman run -it --name client --network foobar quay.io/libpod/alpine_nginx:latest curl http://web/

IIUC,  the expected URL is `http://web.dns.podman`, not `http://web`? Or `http://web` is expected to work too?

**Comment by baude** [comment]
should work as well.

**Comment by rhatdan** [comment]
So is this an issue, or are the documents in fact correct?

**Comment by AkihiroSuda** [comment]
Thanks for clarification, but looking up hostname without .dns.podman suffix doesn't work for my Ubuntu 20.10 host. Maybe some specific configuration is needed for dnsmasq stuff on Ubuntu?

**Comment by baude** [comment]
verified as such @AkihiroSuda I dont understand why.
