### ISSUE TITLE
Using dnsname plugin in rootful podman

### ISSUE THREAD

**Issue by sanyer** [containers/dnsname#63]
Hi! First of all, I'm really enjoying this switch from docker so far. Really like the initiative and documentation.

But currently having an issue of dnsname plugin throwing a warning in rootfull config:
```
WARN[0000] Error validating CNI config file /etc/cni/net.d/87-podman-bridge.conflist: [failed to find plugin "dnsname" in path [/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin]] 
```

Plugin config is added to default network.
Also, networks created in rootfull do not include dnsname plugin.
Am I doing something wrong? Have I missed something?

**Comment by rhatdan** [comment]
Do you have a podman-plugins package installed?

rpm -qf /usr/libexec/cni/dnsname 
podman-plugins-3.1.0-2.fc34.x86_64

**Comment by sanyer** [comment]
oh, true.
I shouldn't been doing that in the middle of the night, completely forgot to check package manager 🥇 

Just installed `podman-dnsname` on Manjaro Linux and everything is fine now.
