### ISSUE TITLE
Not able to stop or restart the containers present in same network after dnsname plugin installation

### ISSUE THREAD

**Issue by snd94** [containers/dnsname#67]
After installing the dnsname plugin built manually from the github(https://github.com/containers/dnsname) facing issue in podman stop or restart.
Machine: RHEL beta 8.4
ERROR:
ERRO[0000] unable to cleanup network for container 6505310e93d4d4587d779fcb882a6266098d39a96ed6052b42a146ac0b11c129: "error tearing down CNI namespace configuration for container 6505310e93d4d4587d779fcb882a6266098d39a96ed6052b42a146ac0b11c129: Error while removing pod from CNI network \"dockerartifacts_service\": stat /run/user/0/containers/cni/dnsname/dockerartifacts_service: no such file or directory"
ERRO[0000] Error adding network: failed to allocate for range 0: 10.89.0.3 has been allocated to 6505310e93d4d4587d779fcb882a6266098d39a96ed6052b42a146ac0b11c129, duplicate allocation is not allowed
ERRO[0000] Error while adding pod to CNI network "dockerartifacts_service": failed to allocate for range 0: 10.89.0.3 has been allocated to 6505310e93d4d4587d779fcb882a6266098d39a96ed6052b42a146ac0b11c129, duplicate allocation is not allowed
Error: error configuring network namespace for container 6505310e93d4d4587d779fcb882a6266098d39a96ed6052b42a146ac0b11c129: failed to allocate for range 0: 10.89.0.3 has been allocated to 6505310e93d4d4587d779fcb882a6266098d39a96ed6052b42a146ac0b11c129, duplicate allocation is not allowed
[root@INBLRGHMAN136LN ~]# podman restart 6505310e93d4
ERRO[0000] Error adding network: failed to allocate for range 0: 10.89.0.3 has been allocated to 6505310e93d4d4587d779fcb882a6266098d39a96ed6052b42a146ac0b11c129, duplicate allocation is not allowed
ERRO[0000] Error while adding pod to CNI network "dockerartifacts_service": failed to allocate for range 0: 10.89.0.3 has been allocated to 6505310e93d4d4587d779fcb882a6266098d39a96ed6052b42a146ac0b11c129, duplicate allocation is not allowed
Error: error configuring network namespace for container 6505310e93d4d4587d779fcb882a6266098d39a96ed6052b42a146ac0b11c129: failed to allocate for range 0: 10.89.0.3 has been allocated to 6505310e93d4d4587d779fcb882a6266098d39a96ed6052b42a146ac0b11c129, duplicate allocation is not allowed

Looks like network is not cleaned up properly /var/lib/cni/networks/. Without the dnsname plugin ip present under this location gets deleted and new one will be getting created, but with this plugin clean up has some issue.

Need some work around for this issue.
Note: Without the dnsname plugin podman start or restart/stop works fine but inter container communication with the continainer works only when dnsname plugin in installed.

**Comment by baude** [comment]
@Luap99 have you ever used dnsname with rootless? i dont think it will work but I have been completely swamped in podman machine these days.  What say you.

**Comment by snd94** [comment]
@baude I am currently using  podman version 3.0.2-dev and it is rootfull. Could you please suggest me the work around to fix this issue if there are any... it will very helpful??

**Comment by Luap99** [comment]
@snd94 Do you have the XDG_RUNTIME_DIR envar set to `/run/user/0` but started the container without this envar? I think dnsname looks at the wrong location because it tries to use XDG_RUNTIME_DIR when present and `/run` if not.

**Comment by Luap99** [comment]
You can remove the offending ip files under `/var/lib/cni/networks/<netname>/...` if you are sure that no other container is using this ip at the moment.

**Comment by snd94** [comment]
@Luap99 I could see ENV variable XDG_RUNTIME_DIR set to /run/user/0 
Yes if i remove those IP's from the dir /var/lib/cni/networks/<netname>/... it works for the next stop/restart, this is kind of manual process. Is there any way to do the network cleanup instead of manually deleting the IPs

**Comment by Luap99** [comment]
@snd94 Does the cleanup fail every time? Can you please provide the exact commands to reproduce.

**Comment by snd94** [comment]
@Luap99 It is sporadic issue after deleting the ip file for some time, since i have 2 containers running on the same network. Based on the error that contains the Ip address need to delete the file from the network path. Only deletion of the file manually is the only solution for this right?

My doubt is is it fine to delete the all the IP's from /var/lib/cni/networks/<netname>/... before doing restart or stop operation on any of the container, does it have any impact on the other container which uses the Ip address present over there?

Either with podman restart containerid or podman stop containerid will throw the same error.
