### ISSUE TITLE
README_PODMAN.md - recommended apparmor_parser commands cause security issues

### ISSUE THREAD

**Issue by cboltz** [containers/dnsname#82]
README_PODMAN.md says in the AppArmor section:

```
Then reload the main dnsmasq profile:

sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.dnsmasq
sudo apparmor_parser /etc/apparmor.d/usr.sbin.dnsmasq
```

The first command unloads the dnsmasq profile - which also means dnsmasq **becomes unconfined**  (= without AppArmor restrictions).

The second command loads the profile, but it can't apply it to the already-running dnsmasq, so this instance **stays unconfined**.

Please change README_PODMAN.md to recommend **reloading** the profile with `apparmor_parser -r` so that dnsmasq stays confined.

The correct and secure version of the section is:

```
Then reload the main dnsmasq profile:

sudo apparmor_parser -r /etc/apparmor.d/usr.sbin.dnsmasq
```

BTW: instead of documenting the need for profile additions, please simply propose them to upstream AppArmor. In many cases, we'll happily add them to the profiles we ship. Actually I just opened https://gitlab.com/apparmor/apparmor/-/merge_requests/800 so future AppArmor releases (> 3.0.3) will probably include these rules.

**Comment by Luap99** [comment]
Please open a PR with your proposed changes.
