### ISSUE TITLE
Can't install: "install: cannot stat 'bin/dnsname': No such file or directory"

### ISSUE THREAD

**Issue by nibbles-bytes** [containers/dnsname#90]
I'm trying to install this plugin but I'm not able to run the make command. Any ideas?
OS: Fedora 35
```
$ podman version:
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.16.14

Built:      Thu Mar 10 12:26:05 2022
OS/Arch:    linux/amd64
```
```
$ go version
go version go1.16.14 linux/amd64
```
I cloned the repo via:
```
git clone https://github.com/containers/dnsname
```

Then ran the make command
```
$ sudo make install PREFIX=/usr
install -Z -d -m 755 /usr/libexec/cni
install -Z -m 755 bin/dnsname /usr/libexec/cni/dnsname
install: cannot stat 'bin/dnsname': No such file or directory
make: *** [Makefile:76: install] Error 1
```

Looking in the Makefile is something not getting set correctly with this line maybe?
```
$(GO_BUILD) -ldflags '$(LDFLAGS_DNSNAME)' -o bin/dnsname github.com/containers/dnsname/plugins/meta/dnsname
```

**Comment by baude** [comment]
If you are using podman 4.0.2, I can only assume you got them from the podman4 copr repo.  As such, it should have installed netavark and aardvark-dns packages.  These replace container networking plugins (cni) and dns name.

If you ran podman v3 on this machine, then run `podman system reset --force`.  Note this will destroy all images, containers, and networks.

**Comment by nibbles-bytes** [comment]
Ah yes that makes sense now. I forgot about the network changes. Thanks!
